version: '3'
services:
  bblfshd:
    image: "bblfsh/bblfshd"
    privileged: true
    entrypoint: "/bin/sh"
    command: ["/start-bblfshd.sh"]
    volumes:
      - ./start-bblfshd.sh:/start-bblfshd.sh
    ports:
      - "9800:9432"
  python-driver:
    image: "bblfsh/python-driver"
    ports:
      - "9801:9432"
  java-driver:
    image: "bblfsh/java-driver"
    ports:
      - "9802:9432"
  python-naive:
    build: ./python
    volumes:
      - ./fixtures:/fixtures
  java-naive:
    build: ./java
    volumes:
      - ./fixtures:/fixtures
